import torch
import torch.nn.functional as F
from torch.nn import ModuleList, Dropout, ReLU, Linear
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_remaining_self_loops, degree, softmax

# ======================================
#               GCN
# ======================================
class GP_GCNConv(MessagePassing):
    """
    Custom GCN Layer that accepts a custom aggregation function
    """
    def __init__(self, in_channels, out_channels, aggr_func=None):
        # 'flow' defines the direction of message propagation (source_to_target is standard)
        # aggr=None because we will handle aggregation manually in the aggregate() method
        super().__init__(aggr=None, flow='source_to_target') 
        
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.aggr_func = aggr_func  # The function generated by DEAP
        
        # standard linear transformation (Theta)
        self.lin = Linear(in_channels, out_channels, bias=False)
        self.bias = torch.nn.Parameter(torch.Tensor(out_channels))

        self.reset_parameters()

    def reset_parameters(self):
        self.lin.reset_parameters()
        self.bias.data.zero_()

    def forward(self, x, edge_index):
        # add self-loops to the adjacency matrix (Standard GCN procedure)
        edge_index, _ = add_remaining_self_loops(edge_index, num_nodes=x.size(0))

        # linear Transformation
        x = self.lin(x)

        # compute Normalization (Node degrees)
        row, col = edge_index
        deg = degree(col, x.size(0), dtype=x.dtype)
        deg_inv_sqrt = deg.pow(-0.5)
        deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # 4. Propagate messages
        # This calls message() and then aggregate() internally
        out = self.propagate(edge_index, x=x, norm=norm)

        # 5. Add bias
        out = out + self.bias

        return out

    def message(self, x_j, norm):
        """
        Constructs messages to node i from each neighbor j.
        x_j: Features of neighbors [num_edges, out_channels]
        norm: Normalization coefficients [num_edges]
        """
        return norm.view(-1, 1) * x_j

    def aggregate(self, inputs, index, ptr=None, dim_size=None):
        """
        Replaces the standard aggregation ('add', 'mean') with the GP function.
        
        Args:
            inputs: Tensor of messages from neighbors [num_edges, out_channels]
            index: Indices of target nodes [num_edges]
            dim_size: Total number of nodes (used for scatter dimensions)
        """
        if self.aggr_func is not None:
            
            if dim_size is None:
                dim_size = int(index.max()) + 1
            
            # arguments for GP Tree signature
            zeros = inputs.new_zeros((dim_size, inputs.size(1)))
            
            
            return self.aggr_func(inputs, index, dim_size,zeros)
            
            
        else:
            raise Exception('A custom aggregation function must be passed.')


class GCN_GP(torch.nn.Module):
    """
    GCN Model that builds the architecture using the custom GP_GCNConv layer.
    """
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers, aggr_func, dropout_rate=0.5):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.aggr_func = aggr_func # Function generated by DEAP
        
        self.layers = ModuleList()
        
        if num_layers == 1:
            # Single layer
            self.layers.append(GP_GCNConv(in_channels, out_channels, aggr_func=self.aggr_func))
        else:
            # Input layer
            self.layers.append(GP_GCNConv(in_channels, hidden_channels, aggr_func=self.aggr_func))
            
            # Hidden layers
            for _ in range(num_layers - 2):
                self.layers.append(GP_GCNConv(hidden_channels, hidden_channels, aggr_func=self.aggr_func))
                
            # Output layer
            self.layers.append(GP_GCNConv(hidden_channels, out_channels, aggr_func=self.aggr_func))
            
        self.relu = ReLU()
        self.dropout = Dropout(p=self.dropout_rate)
        
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        
        # Iterate over all layers except the last one
        for layer in self.layers[:-1]:
            x = layer(x, edge_index)
            x = self.relu(x)
            x = self.dropout(x)
            
        # Last layer (No ReLU/Dropout before softmax in standard GCN)
        x = self.layers[-1](x, edge_index)
        
        return F.log_softmax(x, dim=1)
    


# ======================================
#               SAGE
# ======================================
class GP_SAGEConv(MessagePassing):
    """
    Custom GraphSAGE Layer that uses the GP function to aggregate neighbors.
    Logic: Output = Linear_Self(Node) + Linear_Neigh( Aggr_GP(Neighbors) )
    """
    
    def __init__(self, in_channels, out_channels, aggr_func=None):
        
        super().__init__(aggr=None, flow='source_to_target')
        
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.aggr_func = aggr_func
        
        # GraphSAGE uses two distinct linear weights:
        # 1: transform the features of the node itself (root)
        self.lin_r = Linear(in_channels, out_channels, bias=False)
        # 2:  transform the aggregated features of the neighbors
        self.lin_l = Linear(in_channels, out_channels, bias=True) # Bias is usually here

        self.reset_parameters()
        
    def reset_parameters(self):
        self.lin_r.reset_parameters()
        self.lin_l.reset_parameters()
        
    def forward(self, x, edge_index):
        # linear transformation of self (Root Node)
        # x = [Num_Nodes, In_Channels]
        out_self = self.lin_r(x)

        # propagation (neighbor aggregation via GP)
        out_neigh = self.propagate(edge_index, x=x)
        
        # linear transformation of aggregated neighbors
        out_neigh = self.lin_l(out_neigh)

        # combination
        
        return out_self + out_neigh
    
    
    def message(self, x_j):
        """
        In SAGE, the message is just the raw neighbor feature.
        The GP will decide if it applies ReLU, Identity, etc., before aggregating.
        """
        return x_j
    
    def aggregate(self, inputs, index, ptr=None, dim_size=None):
        """
        inputs: Neighbor features (x_j)
        index: Target indices
        """
        if self.aggr_func is not None:
            # detect feature dimension            
            if dim_size is None:
                dim_size = int(index.max()) + 1

            # arguments for GP Tree signature
            zeros = inputs.new_zeros((dim_size, inputs.size(1)))
            
            # call the evolved function passing all 4 arguments
            return self.aggr_func(inputs, index, dim_size, zeros)
        else:
            raise Exception('GP_SAGEConv: No custom aggregation function passed.')
        
        
class SAGE_GP(torch.nn.Module):
    """
    SAGE Model architecture that builds the network using the custom GP_SAGEConv layer.
    """
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers, aggr_func, dropout_rate=0.5):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.aggr_func = aggr_func
        
        self.layers = ModuleList()
        
        if num_layers == 1:
            self.layers.append(GP_SAGEConv(in_channels, out_channels, aggr_func=self.aggr_func))
        else:
            # input Layer
            self.layers.append(GP_SAGEConv(in_channels, hidden_channels, aggr_func=self.aggr_func))
            
            # hidden Layers
            for _ in range(num_layers - 2):
                self.layers.append(GP_SAGEConv(hidden_channels, hidden_channels, aggr_func=self.aggr_func))
                
            # output Layer
            self.layers.append(GP_SAGEConv(hidden_channels, out_channels, aggr_func=self.aggr_func))
            
        self.relu = ReLU(inplace=False)
        self.dropout = Dropout(p=self.dropout_rate, inplace=False)
        
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        
        for layer in self.layers[:-1]:
            x = layer(x, edge_index)
            x = self.relu(x)
            x = self.dropout(x)
            
        x = self.layers[-1](x, edge_index)
        
        return F.log_softmax(x, dim=1)
    
    
# ======================================
#               GAT
# ======================================


class GP_GATConv(MessagePassing):
    """
    Custom Graph Attention (GAT) Layer with GP-based Aggregation.
    
    The aggregation step is replaced by an evolved GP function.
    Logic: Output = Linear(Aggr_GP( Weighted_Messages )) + Bias
    """
    def __init__(self, in_channels, out_channels, aggr_func=None):
        # We set aggr=None because the GP function handles the aggregation logic
        super().__init__(aggr=None, flow='source_to_target')
        
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.aggr_func = aggr_func
        
        # Standard GAT linear transformation for node features
        self.lin = Linear(in_channels, out_channels, bias=False)
        
        # Learnable attention parameters for source and target nodes
        self.att_src = torch.nn.Parameter(torch.Tensor(1, out_channels))
        self.att_dst = torch.nn.Parameter(torch.Tensor(1, out_channels))
        
        self.bias = torch.nn.Parameter(torch.Tensor(out_channels))
        self.reset_parameters()

    def reset_parameters(self):
        self.lin.reset_parameters()
        torch.nn.init.xavier_uniform_(self.att_src)
        torch.nn.init.xavier_uniform_(self.att_dst)
        self.bias.data.zero_()

    def forward(self, x, edge_index):
        # 1. Add self-loops to ensure nodes consider their own features
        edge_index, _ = add_remaining_self_loops(edge_index, num_nodes=x.size(0))

        # 2. Project input features
        x = self.lin(x)
        
        # 3. Compute attention scores
        # We use keepdim=True to ensure the shape is [N, 1] instead of [N]
        # This prevents internal PyG errors in the propagate/collection phase
        alpha_src = (x * self.att_src).sum(dim=-1, keepdim=True)
        alpha_dst = (x * self.att_dst).sum(dim=-1, keepdim=True)

        # 4. Propagate
        # PyG will automatically map alpha_src to alpha_src_i and alpha_dst to alpha_dst_j
        out = self.propagate(edge_index, x=x, alpha_src=alpha_src, alpha_dst=alpha_dst)

        if self.bias is not None:
            out = out + self.bias
            
        return out

    def message(self, x_j, alpha_src_i, alpha_dst_j, index, ptr, size_i):
        """
        Calculates normalized attention weights and applies them to messages.
        """
        # Since we used keepdim=True, alpha_src_i and alpha_dst_j are now [E, 1]
        alpha = alpha_src_i + alpha_dst_j
        alpha = F.leaky_relu(alpha, 0.2)
        
        # Softmax normalization
        alpha = softmax(alpha, index, ptr, size_i)
        
        # Dropout
        alpha = F.dropout(alpha, p=0.6, training=self.training)
        
        # Weighted message (Both are [E, F] and [E, 1], so broadcasting works)
        return x_j * alpha

    def aggregate(self, inputs, index, ptr=None, dim_size=None):
        """
        Genetic Programming Aggregation.
        'inputs' are messages already weighted by the attention mechanism.
        """
        if self.aggr_func is not None:
            if dim_size is None:
                dim_size = int(index.max()) + 1
            
            # Terminal 'zeros' required by the GP tree signature for type safety
            zeros = inputs.new_zeros((dim_size, inputs.size(1)))
           
            # Execute the evolved GP function
            out = self.aggr_func(inputs, index, dim_size, zeros)

            # --- DIMENSION SAFEGUARDS ---
            # If the GP tree flattens the output to 1D, restore the 2D shape [N, 1]
            if out.dim() == 1:
                out = out.unsqueeze(-1)
            
            # If the GP output column count doesn't match the layer expectation, 
            # expand the tensor to prevent matrix multiplication errors.
            if out.size(1) != inputs.size(1):
                out = out.expand(-1, inputs.size(1))
            
            return out
        else:
            raise Exception('GP_GATConv: No custom aggregation function passed.')


class GAT_GP(torch.nn.Module):
    """
    Standard GAT Model architecture that integrates the custom GP_GATConv layer.
    """
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers, aggr_func, dropout_rate=0.5):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.aggr_func = aggr_func
        self.layers = ModuleList()
        
        # Build the network stack
        if num_layers == 1:
            self.layers.append(GP_GATConv(in_channels, out_channels, aggr_func=self.aggr_func))
        else:
            # Input Layer
            self.layers.append(GP_GATConv(in_channels, hidden_channels, aggr_func=self.aggr_func))
            # Hidden Layers
            for _ in range(num_layers - 2):
                self.layers.append(GP_GATConv(hidden_channels, hidden_channels, aggr_func=self.aggr_func))
            # Output Layer
            self.layers.append(GP_GATConv(hidden_channels, out_channels, aggr_func=self.aggr_func))
            
        self.dropout = Dropout(p=self.dropout_rate, inplace=False)
        
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        
        # Apply layers with ELU activation (standard for GAT) and Dropout
        for layer in self.layers[:-1]:
            x = layer(x, edge_index)
            x = F.elu(x)
            x = self.dropout(x)
        
        # Final layer (no activation here, log_softmax follows)
        x = self.layers[-1](x, edge_index)

        # --- FINAL DIMENSION CHECK ---
        # Ensure the final tensor is 2D [N, Classes] to avoid LogSoftmax errors
        if x.dim() == 1:
            x = x.unsqueeze(1)

        return F.log_softmax(x, dim=1)
# ======================================
#               GIN
# ======================================

class GP_GINConv(MessagePassing):
    """
    Custom GIN Layer with GP Aggregation.
    
    Logic:
    1. Aggregate neighbors using GP (replacing standard Sum).
    2. Add self-loop with a learnable epsilon: (1 + eps) * x_i.
    3. Pass the result through an MLP.
    """
    def __init__(self, mlp, aggr_func=None, train_eps=True):
        
        super().__init__(aggr=None, flow='source_to_target')
        
        self.mlp = mlp
        self.aggr_func = aggr_func
        
        # learnable epsilon parameter
        if train_eps:
            self.eps = torch.nn.Parameter(torch.Tensor([0.0]))
        else:
            self.register_buffer('eps', torch.Tensor([0.0]))

    def forward(self, x, edge_index):
        # propagate (aggregate neighbors via GP)
        # Note: GIN typically doesn't add self-loops to edge_index because it handles the central node x separately via (1+eps).
        out_neigh = self.propagate(edge_index, x=x)

        # combine with Self
        out = out_neigh + (1 + self.eps) * x

        # apply MLP
        return self.mlp(out)

    def message(self, x_j):
        return x_j

    def aggregate(self, inputs, index, ptr=None, dim_size=None):
        if self.aggr_func is not None:
            if dim_size is None:
                dim_size = int(index.max()) + 1
            
            # arguments for GP Tree signature
            zeros = inputs.new_zeros((dim_size, inputs.size(1)))
            return self.aggr_func(inputs, index, dim_size, zeros)
        else:
            raise Exception('GP_GINConv: No custom aggregation function passed.')


class GIN_GP(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers, aggr_func, dropout_rate=0.5):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.aggr_func = aggr_func
        self.layers = ModuleList()
        
        # helper to create MLP
        def make_mlp(input_dim, output_dim):
            return torch.nn.Sequential(
                torch.nn.Linear(input_dim, output_dim),
                torch.nn.ReLU(inplace=False), # Important: inplace=False
                torch.nn.Linear(output_dim, output_dim)
            )

        if num_layers == 1:
             self.layers.append(GP_GINConv(make_mlp(in_channels, out_channels), aggr_func=self.aggr_func))
        else:
            # input
            self.layers.append(GP_GINConv(make_mlp(in_channels, hidden_channels), aggr_func=self.aggr_func))
            # hidden
            for _ in range(num_layers - 2):
                self.layers.append(GP_GINConv(make_mlp(hidden_channels, hidden_channels), aggr_func=self.aggr_func))
            # output
            self.layers.append(GP_GINConv(make_mlp(hidden_channels, out_channels), aggr_func=self.aggr_func))
            
        self.dropout = Dropout(p=self.dropout_rate, inplace=False)
        
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        for layer in self.layers[:-1]:
            x = layer(x, edge_index)
            x = F.relu(x)
            x = self.dropout(x)
        x = self.layers[-1](x, edge_index)
        return F.log_softmax(x, dim=1)